{
 "title": "Monitor_windows_exporterVN",
 "tags": [
  "Prometheus",
  "windows_exporter",
  "monitor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_cs_hostname, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Name",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Tổng quan về tài nguyên (associated JOB item) máy chủ hiện tại: [$show_hostname] : $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job: Server Resource Overview",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
      },
      {
       "expr": "time()-windows_system_system_up_time{job=~\"$job\"}"
      },
      {
       "expr": "windows_cs_logical_processors{job=~\"$job\"}-0"
      },
      {
       "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
      },
      {
       "expr": "100-(avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"}-0"
      },
      {
       "expr": "100-100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "1-(windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C: \"})"
      },
      {
       "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
      },
      {
       "expr": "windows_os_processes{job=~\"$job\"}"
      },
      {
       "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
      }
     ]
    },
    {
     "title": "Mức sử dụng CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100-(avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sử dụng memory ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100.0-100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chi tiết mạng & lưu lượng",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "bps", "label": "Download　　　　Upload" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_Upload",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_download",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Chi tiết đọc và ghi đĩa ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
     "yaxes": [
      { "format": "Bps", "label": "Read　　　　write" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_Read",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_write",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Chi tiết về IO đĩa ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
     "yaxes": [
      { "format": "iops", "label": "Read　　　　write" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "-max by (instance) (irate(windows_logical_disk_reads_total[2m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_Read",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "max by (instance) (irate(windows_logical_disk_writes_total[2m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{instance}}_write",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Chi tiết tài nguyên [$show_hostname: $instance]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Startup time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time()-windows_system_system_up_time{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100-(avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100 "
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100-100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Service Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{state}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Number of Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Number of Processes"
      }
     ]
    },
    {
     "title": "CPU core number",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory details",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Total memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Remaining memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Free virtual memory"
      }
     ]
    },
    {
     "title": "Disk free space",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "remaining space  {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Total volume {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network details",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}} - Sent-Uploaded",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}} - Received-downloaded",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Read and write disk",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk I O",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Use the network",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}) * 100",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "system_threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "system_threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "System exception dispatches",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Chi tiết Service & processes [$show_hostname: $instance]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU per Process",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum(irate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (process, process_id) / ignoring(process, process_id) group_left sum(windows_cs_logical_processors)) * 100)",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Threads per Process",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "windows_process_thread_count{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "graph",
     "description": "bộ nhớ làm việc\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "windows_process_working_set{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Private Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "windows_process_private_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Writes per Process",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(windows_process_io_bytes_total{mode=\"write\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Reads per Process",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(windows_process_io_bytes_total{mode=\"read\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    },
    {
     "title": "Other IO per Process",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "irate(windows_process_io_bytes_total{mode=\"other\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{process}} ({{process_id}})"
      }
     ]
    }
   ]
  }
 ]
}